#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg
  - lsb-release
  - unzip
  - git
  - vim
  - htop
  - net-tools
  - jq
  - python3-pip

write_files:
  - path: /etc/promtail/config.yml
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      
      positions:
        filename: /tmp/positions.yaml
      
      clients:
        - url: ${GRAFANA_LOKI_URL}
          basic_auth:
            username: ${GRAFANA_LOKI_USERNAME}
            password: ${GRAFANA_LOKI_PASSWORD}
      
      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                host: ${PROJECT_NAME}-${ENVIRONMENT}
                __path__: /var/log/*.log
        
        - job_name: docker
          static_configs:
            - targets:
                - localhost
              labels:
                job: docker
                host: ${PROJECT_NAME}-${ENVIRONMENT}
                __path__: /var/lib/docker/containers/*/*.log
        
        - job_name: technitium
          static_configs:
            - targets:
                - localhost
              labels:
                job: technitium-dns
                host: ${PROJECT_NAME}-${ENVIRONMENT}
                __path__: /opt/data/technitium/logs/*.log
        
        - job_name: journal
          journal:
            json: false
            max_age: 12h
            labels:
              job: systemd-journal
              host: ${PROJECT_NAME}-${ENVIRONMENT}
          relabel_configs:
            - source_labels: ['__journal__systemd_unit']
              target_label: 'unit'

  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }

  - path: /home/ubuntu/docker-compose.yml
    content: |
      version: '3.8'

      services:
        ofelia:
          image: mcuadros/ofelia:latest
          container_name: ofelia
          restart: unless-stopped
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./ofelia/config:/etc/ofelia
            - ./ofelia/logs:/var/log/ofelia
          command: daemon --config=/etc/ofelia/config.ini
          networks:
            - hal-network

        technitium:
          image: technitium/dns-server:latest
          container_name: technitium
          hostname: dns-server
          restart: unless-stopped
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "5380:5380/tcp"
            - "67:67/udp"
          environment:
            - DNS_SERVER_DOMAIN=dns.${DOMAIN}
            - DNS_SERVER_ADMIN_PASSWORD=${TECHNITIUM_ADMIN_PASSWORD}
            - DNS_SERVER_PREFER_IPV6=false
            - DNS_SERVER_WEB_SERVICE_HTTP_PORT=5380
            - DNS_SERVER_RECURSION=Allow
            - DNS_SERVER_ENABLE_BLOCKING=false
            - DNS_SERVER_FORWARDERS=1.1.1.1,8.8.8.8
          volumes:
            - technitium-config:/etc/dns
            - technitium-logs:/var/log
          networks:
            - hal-network

      networks:
        hal-network:
          driver: bridge

      volumes:
        technitium-config:
          driver: local
          driver_opts:
            type: none
            o: bind
            device: /opt/data/technitium/config
        technitium-logs:
          driver: local
          driver_opts:
            type: none
            o: bind
            device: /opt/data/technitium/logs

  - path: /home/ubuntu/ofelia/config/config.ini
    content: |
      [global]
      save-folder = /var/log/ofelia
      save-only-on-error = false

      [job-exec "system-update"]
      schedule = @weekly
      container = ofelia
      command = sh -c "apt-get update && apt-get upgrade -y"

      [job-exec "docker-cleanup"]
      schedule = @daily
      container = ofelia
      command = sh -c "docker system prune -af --volumes"

      [job-exec "backup-configs"]
      schedule = @daily
      container = ofelia
      command = sh -c "tar -czf /opt/data/backups/config-$(date +%Y%m%d).tar.gz /opt/data/technitium/config"

  - path: /home/ubuntu/setup-data-dirs.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      # Use local disk for data storage (single 50GB volume)
      DATA_DIR="/opt/data"

      echo "Setting up data directories..."
      mkdir -p $${DATA_DIR}/{technitium/config,technitium/logs,ofelia/config,ofelia/logs,backups}
      chown -R ubuntu:ubuntu $${DATA_DIR}
      
      echo "Data directories created at $${DATA_DIR}"

  - path: /home/ubuntu/.env
    content: |
      DOMAIN=${domain}
      TECHNITIUM_ADMIN_PASSWORD=${technitium_admin_password}
      PROJECT_NAME=${project_name}
      ENVIRONMENT=${environment}

runcmd:
  # Install Promtail for log shipping to Grafana Cloud
  - mkdir -p /etc/promtail
  - curl -s https://api.github.com/repos/grafana/loki/releases/latest | grep browser_download_url | grep promtail-linux-amd64.zip | cut -d '"' -f 4 | wget -qi -
  - unzip promtail-linux-amd64.zip
  - mv promtail-linux-amd64 /usr/local/bin/promtail
  - chmod +x /usr/local/bin/promtail
  - rm promtail-linux-amd64.zip
  
  # Create systemd service for Promtail
  - |
    cat > /etc/systemd/system/promtail.service <<EOF
    [Unit]
    Description=Promtail service
    After=network.target
    
    [Service]
    Type=simple
    User=root
    ExecStart=/usr/local/bin/promtail -config.file=/etc/promtail/config.yml
    Restart=always
    RestartSec=10
    
    [Install]
    WantedBy=multi-user.target
    EOF
  
  - systemctl daemon-reload
  - systemctl enable promtail
  - systemctl start promtail
  
  # Docker installation
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - usermod -aG docker ubuntu
  - systemctl enable docker
  - systemctl start docker
  
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
  - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - apt-get update
  - apt-get install -y terraform vault
  
  - wget -O- https://raw.githubusercontent.com/ansible/ansible/stable-2.16/packaging/debian/ubuntu/ansible.list | tee /etc/apt/sources.list.d/ansible.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  - apt-get update
  - apt-get install -y ansible
  
  - wget -O /tmp/oci-cli.zip https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
  - bash /tmp/oci-cli.zip --accept-all-defaults --exec-dir /usr/local/bin --install-dir /usr/local/lib/oracle-cli
  
  - /home/ubuntu/setup-data-dirs.sh
  
  - cp /home/ubuntu/ofelia/config/config.ini /opt/data/ofelia/config/config.ini
  
  - cd /home/ubuntu && docker compose up -d
  
  - echo "HAL Control Plane setup complete" > /home/ubuntu/setup-complete.txt
  - date >> /home/ubuntu/setup-complete.txt

final_message: "HAL Control Plane is ready after $UPTIME seconds"